### ISSUE TITLE
[BUG] TypeError: Cannot read properties of null (reading 'literal')

### ISSUE THREAD

**Issue by aiko-chan-ai** [bgrnwd/fotmob#482]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Stack Error log:
```js
C:\Users\Elysia\Desktop\src\node_modules\.pnpm\fotmob@2.4.1\node_modules\fotmob\dist\cjs\types\player.js:33
    else if (typeof typ === "object" && typ.literal !== undefined) {
                                            ^

TypeError: Cannot read properties of null (reading 'literal')
    at prettyTypeName (C:\Users\Elysia\Desktop\src\node_modules\.pnpm\fotmob@2.4.1\node_modules\fotmob\dist\cjs\types\player.js:33:45)
    at prettyTypeName (C:\Users\Elysia\Desktop\src\node_modules\.pnpm\fotmob@2.4.1\node_modules\fotmob\dist\cjs\types\player.js:23:35)
    at invalidValue (C:\Users\Elysia\Desktop\src\node_modules\.pnpm\fotmob@2.4.1\node_modules\fotmob\dist\cjs\types\player.js:15:23)  
    at transformUnion (C:\Users\Elysia\Desktop\src\node_modules\.pnpm\fotmob@2.4.1\node_modules\fotmob\dist\cjs\types\player.js:71:16)
    at transform (C:\Users\Elysia\Desktop\src\node_modules\.pnpm\fotmob@2.4.1\node_modules\fotmob\dist\cjs\types\player.js:132:15)    
    at C:\Users\Elysia\Desktop\src\node_modules\.pnpm\fotmob@2.4.1\node_modules\fotmob\dist\cjs\types\player.js:105:32
    at Array.forEach (<anonymous>)
    at transformObject (C:\Users\Elysia\Desktop\src\node_modules\.pnpm\fotmob@2.4.1\node_modules\fotmob\dist\cjs\types\player.js:100:43)
    at transform (C:\Users\Elysia\Desktop\src\node_modules\.pnpm\fotmob@2.4.1\node_modules\fotmob\dist\cjs\types\player.js:136:23)
    at cast (C:\Users\Elysia\Desktop\src\node_modules\.pnpm\fotmob@2.4.1\node_modules\fotmob\dist\cjs\types\player.js:144:12)

Node.js v22.4.1
```

### Expected Behavior

If I use the ID 1071179 (as in the example), no errors occur.
I want it to work normally like some other examples.

### Steps To Reproduce

Code test:

```js
import Fotmob from "fotmob";
const fotmob = new Fotmob();

let player = await fotmob.getPlayer("30981") // Lionel Messi
```

### Environment

```Markdown
- OS: Windows 10 x64 (19045.4651)
- Node: 22.4.1
- npm: 10.8.1
```

### Version

2.4.1

### Anything else?

It could be because you're using `typeof`, as `typeof null` returns `object`.

**Comment by kuijpie** [comment]
@aiko-chan-ai I had the same issue, with some id's it doesn't seem to work. Using the following work around, which seem to work with all id's:
`const player = await fotmob.request("playerData", { id: `${playerId}` });`

**Comment by ItamarShDev** [comment]
could not reproduce. will investigate

**Comment by aiko-chan-ai** [comment]
The latest version has resolved the issue; I'm not sure if it's because the API is no longer returning error data
